name: Snapshot

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:

env:
  CHART_NAME: nginx-sandbox

jobs:
  generate-matrix:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      values: ${{ steps.set-matrix.outputs.values }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: generate matrix values
        id: set-matrix
        run: echo "values=$(.github/generate-snapshot-matrix.sh)" >> "$GITHUB_OUTPUT"

  generate-manifests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: generate manifests
        run: |
          tests/generate.sh gen "$CHART_NAME" generated
          mv tests/${CHART_NAME}/generated .
      - name: upload manifests
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: generated-manifests
          path: generated
          retention-days: 1

  test:
    needs:
      - generate-matrix
      - generate-manifests
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        value: ${{ fromJson(needs.generate-matrix.outputs.values) }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: download artifacts
        uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8.0.2
        with:
          name: generated-manifests
          path: generated
      - name: move golden
        run: mv tests/${CHART_NAME}/golden .
      - name: objdiff
        uses: berquerant/k8s-object-diff@4cf82d66d3d1a9ae6e46440a7f38316c426fb02b # v0.6.0
        id: objdiff
        with:
          left: golden/${{ matrix.value }}
          right: generated/${{ matrix.value }}
          fail-on-diff: true
